# Generated by Django 4.1.2 on 2022-11-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceschool', '0002_alter_profile_balance_alter_profile_photo'),
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_groups', to='danceschool.commands')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_group', to='calendarapp.event')),
            ],
            options={
                'unique_together': {('event', 'command')},
            },
        ),
    ]
