# Generated by Django 4.1.2 on 2022-11-07 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coin', models.CharField(max_length=100, null=True)),
                ('performed', models.BooleanField()),
                ('icon', models.CharField(choices=[(models.CharField(max_length=100, null=True), 'coin')], max_length=10, null=True)),
                ('text', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=43)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Введите имя пользователя', max_length=30)),
                ('last_name', models.CharField(help_text='Введите фамилию пользователя', max_length=30)),
                ('photo', models.ImageField(help_text='Загрузите фотографию пользователя', upload_to='profiles/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.CharField(default=0, help_text='Введите баланс DanceCoin', max_length=6)),
                ('energy', models.IntegerField(default=0, help_text='Введите баланс энергии')),
                ('category', models.CharField(choices=[('DD media', 'DDM'), ('Mentor', 'M'), ('Dancer', 'D'), ('Team Leader', 'TL'), ('Trainer', 'T'), ('Admin', 'Adm')], default='Adm', help_text='Выберете категорию пользователя', max_length=20)),
                ('rang', models.CharField(choices=[('junior', 'jun'), ('middle', 'mid'), ('senior', 'sen'), ('vice president', 'VP')], default='sen', help_text='Выберете ранг пользователя', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at', '-first_name', '-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energy', models.IntegerField(default=0, null=True)),
                ('sun', models.IntegerField(default=0, null=True)),
                ('water', models.IntegerField(default=0, null=True)),
                ('timer', models.TimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='danceschool.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_created', to='danceschool.profile')),
                ('members', models.ManyToManyField(related_name='user_teams', to='danceschool.profile')),
            ],
        ),
    ]
