# Generated by Django 4.1.2 on 2022-11-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, help_text='Введите баланс DanceCoin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию пользователя', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
